version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
    volumes:
      - ./data/mysql:/var/lib/mysql

volumes:
  mysql_data:
